set BaseFee to nil
scroll-tech/go-ethereum pull request #222
Opened 2023-02-17 14:42 UTC by NazariiDenha

When computing the block hash, `l2geth` uses the whole block (including `BaseFee`). but the RPC client (e.g. SDK) does not receive `BaseFee` so the hash will be different.

we want to make sure we set `BaseFee` to `nil` inside `l2geth` too.

1. change it to `nil` in `worker.go` here: https://github.com/scroll-tech/go-ethereum/pull/206/files#diff-689874b30f6f905ce6c47cdefeddcf052b467a7936a981f4b6cf38939e10d924R933
2. do a `nil`-check everywhere `BaseFee` is used,

2023-02-17 16:11 UTC, colinlyguo commented on cmd/evm/internal/t8ntool/transition.go
> +		if prestate.Env.BaseFee == nil && !(chainConfig.EnableEIP2718 && chainConfig.EnableEIP1559) {
```suggestion
		if prestate.Env.BaseFee == nil && (chainConfig.EnableEIP2718 || chainConfig.EnableEIP1559) {
```

2023-02-17 16:11 UTC, colinlyguo commented on cmd/evm/internal/t8ntool/transition.go
> +		if prestate.Env.BaseFee == nil && !(chainConfig.EnableEIP2718 && chainConfig.EnableEIP1559) {
```suggestion
		if prestate.Env.BaseFee == nil && chainConfig.EnableEIP2718 && chainConfig.EnableEIP1559 {
```

2023-02-17 16:13 UTC, colinlyguo commented on consensus/misc/eip1559.go
> +	if !(config.EnableEIP2718 && config.EnableEIP1559) {
```suggestion
	if !config.EnableEIP2718 || !config.EnableEIP1559 {
```

2023-02-17 16:15 UTC, colinlyguo commented on core/state_transition.go
> +			if st.evm.Context.BaseFee == nil && st.gasFeeCap.Cmp(big.NewInt(0)) < 0 {
we don't need this?

2023-02-17 16:20 UTC, colinlyguo approved these changes, later dismissed
Some questions about the `if` condition, otherwise LGTM.

2023-02-20 14:12 UTC, zimpha submitted a review, later dismissed

2023-02-20 15:02 UTC, colinlyguo approved these changes, later dismissed

2023-02-20 15:37 UTC, Thegaram requested changes
Please update `genesis.go` so that we can initialize genesis with `BaseFee = nil`.

2023-02-20 16:26 UTC, Thegaram approved these changes

2023-02-20 16:37 UTC, colinlyguo approved these changes

2023-02-21 06:01 UTC, icemelon approved these changes

2023-02-21 06:04 UTC, merged