(feat) implement EIP-1153 - transient storage
scroll-tech/go-ethereum pull request #701
Opened 2024-04-15 13:20 UTC by NazariiDenha

## 1. Purpose or design rationale of this PR

https://eips.ethereum.org/EIPS/eip-1153
https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/cancun.md
https://www.notion.so/scrollzkp/Add-tload-tstore-opcodes-to-l2geth-8a54dbbcdb894ebd8e6d9c4d46b6de9a?pvs=4

## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [ ] build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- [ ] ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- [ ] docs: Documentation-only changes
- [x] feat: A new feature
- [ ] fix: A bug fix
- [ ] perf: A code change that improves performance
- [ ] refactor: A code change that doesn't fix a bug, or add a feature, or improves performance
- [ ] style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] test: Adding missing tests or correcting existing tests

## 3. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [ ] This PR doesn't involve a new deployment, git tag, docker image tag, and it doesn't affect traces
- [x] Yes

## 4. Breaking change label

Does this PR have the `breaking-change` label?

- [ ] This PR is not a breaking change
- [ ] Yes

2024-04-24 06:11 UTC, HAOYUatHZ commented
personally I will prefer break https://github.com/scroll-tech/go-ethereum/pull/701/commits/34a13ff7bba7bd46b80579e195a19b0dcd34abbe into
+ cherry-pick https://github.com/ethereum/go-ethereum/pull/27613/files
+ enable 1153

2024-04-24 09:51 UTC, Thegaram requested changes

2024-04-24 09:51 UTC, Thegaram commented on core/vm/jump_table.go
> +	enable1153(&instructionSet)
Let's keep this PR open for now. We have not decided whether this should go into Curie or Descartes.

2024-04-25 09:34 UTC, Thegaram commented on core/state/statedb.go
> +	if rules.IsBerlin {
This part is not the same as in upstream: https://github.com/ethereum/go-ethereum/blob/master/core/state/statedb.go#L1277

2024-04-25 09:34 UTC, Thegaram commented on core/state/transient_storage.go
> +	if _, ok := t[addr]; !ok {
Also: https://github.com/ethereum/go-ethereum/blob/master/core/state/transient_storage.go#L37

2024-04-25 09:34 UTC, Thegaram commented on core/vm/interface.go
> +	GetTransientState(addr common.Address, key common.Hash) common.Hash
```suggestion

	GetTransientState(addr common.Address, key common.Hash) common.Hash
```

2024-04-25 09:44 UTC, NazariiDenha commented
closing in favour for new PR

2024-04-25 09:44 UTC, closed without merging