feat: turn libscroll_zstd dynamic lib into static
scroll-tech/go-ethereum pull request #794
Opened 2024-06-03 18:27 UTC by colinlyguo

## 1. Purpose or design rationale of this PR

Simplify the building workflow.
Support running unit tests and building nccc_geth in darwin arm64.

## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] feat: A new feature

## 3. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [x] Yes

## 4. Breaking change label

Does this PR have the `breaking-change` label?

- [x] This PR is not a breaking change

2024-06-04 01:36 UTC, zimpha approved these changes, later dismissed

2024-06-04 01:39 UTC, HAOYUatHZ approved these changes

2024-06-04 02:22 UTC, georgehao approved these changes, later dismissed

2024-06-04 06:12 UTC, HAOYUatHZ requested changes
this PR depends on https://github.com/scroll-tech/da-codec/pull/8
but https://github.com/scroll-tech/da-codec/pull/8 needs improvement

2024-06-04 06:15 UTC, zimpha commented
> this PR depends on [scroll-tech/da-codec#8](https://github.com/scroll-tech/da-codec/pull/8) but [scroll-tech/da-codec#8](https://github.com/scroll-tech/da-codec/pull/8) needs improvement

Or we can add in README to tell devs how to compile the dynamic lib in their local machine.

2024-06-05 04:56 UTC, colinlyguo commented on build/ci.go
> +	gobuild.Args = append(gobuild.Args, "-ldflags", "-extldflags -ldl")
added this line because I have not found a good way to pass env variables when compiling.

2024-06-05 07:29 UTC, colinlyguo commented
tested in local testnet.

2024-06-05 08:17 UTC, zimpha approved these changes, later dismissed

2024-06-05 08:48 UTC, georgehao approved these changes, later dismissed

2024-06-05 08:59 UTC, zimpha approved these changes

2024-06-05 09:00 UTC, HAOYUatHZ approved these changes

2024-06-05 09:22 UTC, merged